# -*- coding: utf-8 -*-
"""module_0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/105bytllNp1aJUH7aUzrWBlehCB2WZ_Vh
"""

import numpy as np

def score_game(game_core):
    '''Запускаем игру 1000 раз, чтобы узнать, как быстро игра угадывает число'''
    count_ls = []
    np.random.seed(27)  # фиксируем RANDOM SEED, чтобы ваш эксперимент был 
                        #воспроизводим!
    random_array = np.random.randint(1,101, size=(1000))
    for number in random_array:
        count_ls.append(game_core(number))
    score = int(np.mean(count_ls))
    print(f"Ваш алгоритм угадывает число в среднем за {score} попыток")
    return(score)


def game_core_v2(number):
    '''Сначала устанавливаем random число от 1 до 10, а потом уменьшаем или 
       увеличиваем его в зависимости от того, больше оно или меньше нужного, 
       цикл несколько раз.'''
    count = 1
    predict = np.random.randint(1,10)
    while number!=predict:
      count +=1
      if number>predict: 
        predict +=10
        if number>predict:
          predict +=5
        elif number<predict:
          predict -=5
      elif number<predict: 
          predict -=1
    return(count) # выход из цикла, если угадали

score_game(game_core_v2)

